import { Button, Card, Col, Descriptions, Drawer, Form, Input, InputNumber, Modal, Progress, Row, Space, Statistic, Table, Tag, Typography, message } from 'antd';
import { DownloadOutlined, EyeOutlined, PlusOutlined, ReloadOutlined } from '@ant-design/icons';
import { useEffect, useState } from 'react';
import type { CreateExportRequest, DashboardOverview, DashboardTrendPoint, ExportTask } from '@xiaoa/share/types';
import { sharedApi } from '../services/sharedApi';

interface PageProps { title: string; description: string; }
function formatDate(value?: string | null) { return value ? new Date(value).toLocaleString('zh-CN') : '-'; }
function PageHeading({ title, description, action }: PageProps & { action?: React.ReactNode }) { return <div className="page-heading"><div className="page-heading-copy"><Typography.Title level={2}>{title}</Typography.Title><Typography.Text>{description}</Typography.Text></div><div className="page-actions">{action}</div></div>; }

// ===== 运营总览看板 =====
export function OperationDashboardPage({ title, description }: PageProps) {
  const [overview, setOverview] = useState<DashboardOverview | null>(null); const [trend, setTrend] = useState<DashboardTrendPoint[]>([]); const [loading, setLoading] = useState(false);
  const load = () => { setLoading(true); Promise.all([sharedApi.getAdminDashboardOverview(), sharedApi.getAdminDashboardTrend()]).then(([o, t]) => { setOverview(o); setTrend(t); }).catch(() => message.error('运营看板加载失败')).finally(() => setLoading(false)); }; useEffect(load, []);
  const maxWork = Math.max(1, ...trend.map((p) => p.workCount ?? 0));
  return <Space direction="vertical" size={20} className="full-width"><PageHeading title={title} description={description} action={<Button icon={<ReloadOutlined />} loading={loading} onClick={load}>刷新</Button>} /><Row gutter={16}>{[{ title: '租户总数', value: overview?.tenantCount, suffix: '' }, { title: '活跃租户', value: overview?.activeTenantCount, suffix: '' }, { title: '门店数', value: overview?.storeCount, suffix: '' }, { title: '会员总数', value: overview?.memberCount, suffix: '' }, { title: '作品总数', value: overview?.workCount, suffix: '' }, { title: '已发布', value: overview?.publishedWorkCount, suffix: '' }, { title: '待审素材', value: overview?.pendingAssetCount, suffix: '' }, { title: '算力用量', value: overview?.quotaUsed, suffix: ' / ' + (overview?.quotaTotal ?? 0) }].map((m) => <Col key={m.title} xs={12} sm={8} md={6}><Card><Statistic title={m.title} value={m.value ?? 0} suffix={m.suffix} /></Card></Col>)}</Row><Card title={`作品产出趋势（近 ${trend.length} 天）`}>{trend.length === 0 ? <Typography.Text type="secondary">暂无趋势数据</Typography.Text> : trend.map((p) => <div key={p.date} style={{ marginBottom: 8 }}><Typography.Text style={{ width: 100, display: 'inline-block' }}>{p.date}</Typography.Text><Progress percent={Math.round(((p.workCount ?? 0) / maxWork) * 100)} format={() => `${p.workCount ?? 0} 件`} style={{ width: 'calc(100% - 110px)', display: 'inline-block', verticalAlign: 'middle' }} /></div>)}</Card></Space>;
}

// ===== 导出任务 =====
function ExportCreateModal({ open, onClose, onSuccess }: { open: boolean; onClose: () => void; onSuccess: () => void }) {
  const [form] = Form.useForm<CreateExportRequest>(); const [loading, setLoading] = useState(false);
  useEffect(() => { if (open) form.resetFields(); }, [open, form]);
  const submit = async () => { try { const values = await form.validateFields(); setLoading(true); await sharedApi.createExportTask(values); message.success('导出任务已创建'); onClose(); onSuccess(); } catch (e) { if (e instanceof Error) message.error(e.message); } finally { setLoading(false); } };
  return <Modal title="创建导出任务" open={open} onCancel={onClose} onOk={submit} confirmLoading={loading} destroyOnClose><Form form={form} layout="vertical"><Form.Item name="type" label="导出类型" rules={[{ required: true }]}><Input placeholder="如 works / members / assets" /></Form.Item><Form.Item name="orgId" label="组织 ID（可选）"><InputNumber className="full-input" /></Form.Item><Form.Item name="dateFrom" label="开始日期"><Input placeholder="YYYY-MM-DD" /></Form.Item><Form.Item name="dateTo" label="结束日期"><Input placeholder="YYYY-MM-DD" /></Form.Item></Form></Modal>;
}
function ExportDetailDrawer({ task, open, onClose }: { task: ExportTask | null; open: boolean; onClose: () => void }) {
  return <Drawer title="导出任务详情" width={480} open={open} onClose={onClose}>{task && <Descriptions bordered column={1} size="small"><Descriptions.Item label="任务 ID">{task.id}</Descriptions.Item><Descriptions.Item label="类型">{task.type || '-'}</Descriptions.Item><Descriptions.Item label="状态"><Tag color={task.status === 'DONE' || task.status === 'SUCCESS' ? 'green' : task.status === 'FAILED' ? 'red' : 'processing'}>{task.status || '-'}</Tag></Descriptions.Item><Descriptions.Item label="行数">{task.rowCount ?? '-'}</Descriptions.Item><Descriptions.Item label="创建时间">{formatDate(task.createdAt)}</Descriptions.Item><Descriptions.Item label="完成时间">{formatDate(task.finishedAt)}</Descriptions.Item><Descriptions.Item label="下载链接">{task.fileUrl ? <Button type="link" icon={<DownloadOutlined />} href={task.fileUrl} target="_blank">下载文件</Button> : '生成中或无文件'}</Descriptions.Item></Descriptions>}</Drawer>;
}
export function ExportAdminPage({ title, description }: PageProps) {
  const [tasks, setTasks] = useState<ExportTask[]>([]); const [loading, setLoading] = useState(false); const [createOpen, setCreateOpen] = useState(false); const [detail, setDetail] = useState<ExportTask | null>(null); const [detailOpen, setDetailOpen] = useState(false);
  const load = () => { setLoading(true); sharedApi.getExportTasks().then(setTasks).catch(() => message.error('导出任务列表加载失败')).finally(() => setLoading(false)); }; useEffect(load, []);
  const viewDetail = (task: ExportTask) => { sharedApi.getExportTask(task.id).then((full) => { setDetail(full); setDetailOpen(true); }).catch(() => message.error('详情加载失败')); };
  return <Space direction="vertical" size={20} className="full-width"><PageHeading title={title} description={description} action={<Button type="primary" icon={<PlusOutlined />} onClick={() => setCreateOpen(true)}>创建导出</Button>} /><Card><div className="table-toolbar"><Typography.Text type="secondary">共 {tasks.length} 个任务</Typography.Text><Button icon={<ReloadOutlined />} onClick={load}>刷新</Button></div><Table loading={loading} rowKey={(r) => String(r.id)} dataSource={tasks} pagination={{ pageSize: 10 }} columns={[{ title: '任务 ID', dataIndex: 'id' }, { title: '类型', dataIndex: 'type' }, { title: '状态', dataIndex: 'status', render: (v) => <Tag color={v === 'DONE' || v === 'SUCCESS' ? 'green' : v === 'FAILED' ? 'red' : 'processing'}>{v || '-'}</Tag> }, { title: '行数', dataIndex: 'rowCount', render: (v) => v ?? '-' }, { title: '创建时间', dataIndex: 'createdAt', render: formatDate }, { title: '操作', render: (_, t) => <Space><Button type="link" icon={<EyeOutlined />} onClick={() => viewDetail(t)}>详情</Button>{t.fileUrl && <Button type="link" icon={<DownloadOutlined />} href={t.fileUrl} target="_blank">下载</Button>}</Space> }]} /></Card><ExportCreateModal open={createOpen} onClose={() => setCreateOpen(false)} onSuccess={load} /><ExportDetailDrawer task={detail} open={detailOpen} onClose={() => setDetailOpen(false)} /></Space>;
}
