import { Button, Card, Drawer, Form, Input, Popconfirm, Space, Table, Tag, Typography, message } from 'antd';
import { DeleteOutlined, EditOutlined, PlusOutlined, ReloadOutlined } from '@ant-design/icons';
import { useEffect, useState } from 'react';
import type { ContentPackage, CreateContentPackageRequest, CreateStyleRequest, StyleOption, UpdateStyleRequest } from '@xiaoa/share/types';
import { sharedApi } from '../services/sharedApi';

interface PageProps { title: string; description: string; }
function formatDate(value?: string | null) { return value ? new Date(value).toLocaleString('zh-CN') : '-'; }
function PageHeading({ title, description, action }: PageProps & { action?: React.ReactNode }) { return <div className="page-heading"><div className="page-heading-copy"><Typography.Title level={2}>{title}</Typography.Title><Typography.Text>{description}</Typography.Text></div><div className="page-actions">{action}</div></div>; }
function useError() { const [error, setError] = useState(''); return { error, catchError: (e: unknown, fallback: string) => setError(e instanceof Error ? e.message : fallback) }; }

// ===== 内容包管理 =====
function PackageDrawer({ open, onClose, onSuccess }: { open: boolean; onClose: () => void; onSuccess: () => void }) {
  const [form] = Form.useForm<CreateContentPackageRequest>(); const [loading, setLoading] = useState(false);
  useEffect(() => { if (open) form.resetFields(); }, [open, form]);
  const submit = async () => { try { const values = await form.validateFields(); setLoading(true); await sharedApi.createContentPackage(values); message.success('内容包已创建'); onClose(); onSuccess(); } catch (e) { if (e instanceof Error) message.error(e.message); } finally { setLoading(false); } };
  return <Drawer title="创建内容包" width={480} open={open} onClose={onClose} extra={<Button type="primary" loading={loading} onClick={submit}>保存</Button>} destroyOnClose><Form form={form} layout="vertical"><Form.Item name="name" label="内容包名称" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="scene" label="适用场景"><Input placeholder="如 520 / 七夕 / 婚礼季" /></Form.Item><Form.Item name="description" label="说明"><Input.TextArea rows={4} /></Form.Item><Form.Item name="startAt" label="开始日期"><Input placeholder="YYYY-MM-DD" /></Form.Item><Form.Item name="endAt" label="结束日期"><Input placeholder="YYYY-MM-DD" /></Form.Item></Form></Drawer>;
}
export function ContentPackagePage({ title, description }: PageProps) {
  const [packages, setPackages] = useState<ContentPackage[]>([]); const [loading, setLoading] = useState(false); const [open, setOpen] = useState(false); const { error, catchError } = useError();
  const load = () => { setLoading(true); sharedApi.getContentPackages().then(setPackages).catch((e) => catchError(e, '内容包列表加载失败')).finally(() => setLoading(false)); }; useEffect(load, []);
  return <Space direction="vertical" size={20} className="full-width"><PageHeading title={title} description={description} action={<Button type="primary" icon={<PlusOutlined />} onClick={() => setOpen(true)}>创建内容包</Button>} />{error && <Typography.Text type="danger">{error}</Typography.Text>}<Card><Table loading={loading} rowKey={(r) => String(r.id)} dataSource={packages} pagination={{ pageSize: 10 }} columns={[{ title: '名称', dataIndex: 'name' }, { title: '场景', dataIndex: 'scene', render: (v) => v || '-' }, { title: '素材数', dataIndex: 'assetCount', render: (v) => v ?? 0 }, { title: '状态', dataIndex: 'status', render: (v) => <Tag color={String(v) === '1' || String(v) === 'ACTIVE' ? 'green' : 'default'}>{String(v) === '1' || String(v) === 'ACTIVE' ? '启用' : '停用'}</Tag> }, { title: '周期', render: (_, p) => `${p.startAt || '-'} ~ ${p.endAt || '-'}` }, { title: '创建时间', dataIndex: 'createdAt', render: formatDate }, { title: '操作', render: (_, p) => <Popconfirm title="停用该内容包？" onConfirm={() => sharedApi.disableContentPackage(p.id).then(load).catch(() => message.error('停用失败'))}><Button type="link" danger icon={<DeleteOutlined />}>停用</Button></Popconfirm> }]} /></Card><PackageDrawer open={open} onClose={() => setOpen(false)} onSuccess={load} /></Space>;
}

// ===== 风格库 =====
function StyleDrawer({ open, style, onClose, onSuccess }: { open: boolean; style: StyleOption | null; onClose: () => void; onSuccess: () => void }) {
  const [form] = Form.useForm<CreateStyleRequest & UpdateStyleRequest>(); const [loading, setLoading] = useState(false);
  useEffect(() => { if (open) form.setFieldsValue(style ? { name: style.name, description: style.description, prompt: style.prompt, sortOrder: style.sortOrder } : { sortOrder: 0 }); }, [open, style, form]);
  const submit = async () => { try { const values = await form.validateFields(); setLoading(true); if (style) await sharedApi.updateStyle(style.id, values); else await sharedApi.createStyle(values); message.success(style ? '风格已更新' : '风格已创建'); onClose(); onSuccess(); } catch (e) { if (e instanceof Error) message.error(e.message); } finally { setLoading(false); } };
  return <Drawer title={style ? '编辑风格' : '新建风格'} width={460} open={open} onClose={onClose} extra={<Button type="primary" loading={loading} onClick={submit}>保存</Button>} destroyOnClose><Form form={form} layout="vertical"><Form.Item name="name" label="风格名称" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="description" label="适用场景描述"><Input.TextArea rows={3} /></Form.Item><Form.Item name="prompt" label="Prompt 指令"><Input.TextArea rows={4} /></Form.Item><Form.Item name="sortOrder" label="排序"><Input /></Form.Item></Form></Drawer>;
}
export function StyleAdminPage({ title, description }: PageProps) {
  const [styles, setStyles] = useState<StyleOption[]>([]); const [loading, setLoading] = useState(false); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<StyleOption | null>(null); const { error, catchError } = useError();
  const load = () => { setLoading(true); sharedApi.getStyleOptions().then(setStyles).catch((e) => catchError(e, '风格列表加载失败')).finally(() => setLoading(false)); }; useEffect(load, []);
  return <Space direction="vertical" size={20} className="full-width"><PageHeading title={title} description={description} action={<Button type="primary" icon={<PlusOutlined />} onClick={() => { setEditing(null); setOpen(true); }}>新建风格</Button>} />{error && <Typography.Text type="danger">{error}</Typography.Text>}<Card><Table loading={loading} rowKey={(r) => String(r.id)} dataSource={styles} pagination={{ pageSize: 10 }} columns={[{ title: '风格名', dataIndex: 'name' }, { title: '适用场景', dataIndex: 'description', ellipsis: true }, { title: 'Prompt', dataIndex: 'prompt', ellipsis: true, render: (v) => v || '-' }, { title: '排序', dataIndex: 'sortOrder', render: (v) => v ?? 0 }, { title: '状态', dataIndex: 'enabled', render: (v) => <Tag color={v === 1 || v === true ? 'green' : 'default'}>{v === 1 || v === true ? '启用' : '停用'}</Tag> }, { title: '操作', render: (_, s) => <Space><Button type="link" icon={<EditOutlined />} onClick={() => { setEditing(s); setOpen(true); }}>编辑</Button><Popconfirm title="确认删除该风格？" onConfirm={() => sharedApi.deleteStyle(s.id).then(load).catch(() => message.error('删除失败'))}><Button type="link" danger>删除</Button></Popconfirm></Space> }]} /></Card><StyleDrawer open={open} style={editing} onClose={() => setOpen(false)} onSuccess={load} /></Space>;
}
