import { Alert, Button, Card, Col, DatePicker, Drawer, Form, Input, Modal, Row, Select, Space, Table, Tag, Typography, message } from 'antd';
import { EditOutlined, EyeOutlined, PlusOutlined, ReloadOutlined, RollbackOutlined } from '@ant-design/icons';
import { useEffect, useState } from 'react';
import type { AIGenerationType, GenerationTaskMonitor, GenerationTaskQuery, PromptTemplate, PromptTemplateRequest, WorkGenerationStatus } from '@xiaoa/share/types';
import { sharedApi } from '../services/sharedApi';

const sceneLabels: Record<AIGenerationType, string> = { IMAGE: '图文', VIDEO: '视频' };
const statusLabels: Record<string, string> = { PENDING: '生成中', PROCESSING: '生成中', '0': '生成中', SUCCESS: '成功', '1': '成功', FAILED: '失败', '2': '失败' };
const statusColors: Record<string, string> = { PENDING: 'processing', PROCESSING: 'processing', '0': 'processing', SUCCESS: 'success', '1': 'success', FAILED: 'error', '2': 'error' };
const promptVariables = '{{style}} {{platform}} {{userInput}} {{scriptRef}}';

function formatDate(value?: string) { return value ? new Date(value).toLocaleString('zh-CN') : '-'; }
function statusTag(status: WorkGenerationStatus | PromptTemplate['status']) { const key = String(status); return <Tag color={statusColors[key] || (key === 'ACTIVE' || key === '1' ? 'green' : 'default')}>{statusLabels[key] || (key === 'ACTIVE' || key === '1' ? '启用' : key === 'INACTIVE' || key === '0' ? '停用' : key)}</Tag>; }
function PageHeading({ title, description, action }: { title: string; description: string; action?: React.ReactNode }) { return <div className="page-heading"><div className="page-heading-copy"><Typography.Title level={2}>{title}</Typography.Title><Typography.Text>{description}</Typography.Text></div><div className="page-actions">{action}</div></div>; }

function PromptEditor({ open, template, onClose, onSuccess }: { open: boolean; template: PromptTemplate | null; onClose: () => void; onSuccess: () => void }) {
  const [form] = Form.useForm<PromptTemplateRequest>(); const [preview, setPreview] = useState(''); const [loading, setLoading] = useState(false);
  useEffect(() => { const content = template?.content || ''; form.setFieldsValue({ scene: template?.scene || 'IMAGE', content }); setPreview(content); }, [form, template, open]);
  const submit = async (values: PromptTemplateRequest) => { try { setLoading(true); await sharedApi.createPromptTemplate(values); message.success('已提交新版本，旧版本会保留'); onClose(); onSuccess(); } catch (error) { if (error instanceof Error) message.error(error.message); } finally { setLoading(false); } };
  const renderPreview = (content: string) => content.replace(/\{\{style\}\}/g, '轻奢').replace(/\{\{platform\}\}/g, '朋友圈').replace(/\{\{userInput\}\}/g, '520限定礼盒，突出限定感').replace(/\{\{scriptRef\}\}/g, '门店商品素材');
  return <Drawer title={template ? `编辑模板 · v${template.version}` : '新建 Prompt 模板'} width={760} open={open} onClose={onClose} destroyOnClose extra={<Button type="primary" loading={loading} onClick={() => form.submit()}>保存为新版本</Button>}><Alert type="info" showIcon message="编辑保存会创建新版本，不覆盖历史版本" description={`可用变量：${promptVariables}`} /><Form form={form} layout="vertical" onFinish={submit} style={{ marginTop: 20 }}><Form.Item name="scene" label="适用场景" rules={[{ required: true }]}><Select options={[{ value: 'IMAGE', label: '图文' }, { value: 'VIDEO', label: '视频' }]} /></Form.Item><Form.Item name="content" label="模板内容" rules={[{ required: true, message: '请输入模板内容' }]}><Input.TextArea rows={14} className="prompt-template-editor" onChange={(event) => { setPreview(event.target.value); }} placeholder="你是珠宝门店营销专家..." /></Form.Item></Form><Card size="small" title="变量替换预览"><Typography.Paragraph className="prompt-preview">{renderPreview(preview) || '输入模板后预览变量替换效果'}</Typography.Paragraph></Card></Drawer>;
}

export function PromptTemplatesPage() {
  const [templates, setTemplates] = useState<PromptTemplate[]>([]); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(false); const [scene, setScene] = useState<AIGenerationType | undefined>(); const [editorOpen, setEditorOpen] = useState(false); const [editing, setEditing] = useState<PromptTemplate | null>(null);
  const load = () => { setLoading(true); sharedApi.getPromptTemplates({ pageNo: 1, pageSize: 50, scene }).then((result) => { setTemplates(result.list); setTotal(result.total); }).catch((error) => message.error(error instanceof Error ? error.message : 'Prompt 模板加载失败')).finally(() => setLoading(false)); }; useEffect(load, [scene]);
  const rollback = (template: PromptTemplate) => sharedApi.rollbackPromptTemplate(template.id).then(() => { message.success(`已回滚到 v${template.version}`); load(); }).catch((error) => message.error(error instanceof Error ? error.message : '回滚失败'));
  return <Space direction="vertical" size={20} className="full-width"><PageHeading title="Prompt 模板管理" description="维护后端 AI prompt 模板，保存会生成新版本，不在前端拼装 prompt。" action={<Space><Select allowClear placeholder="场景" style={{ width: 110 }} value={scene} onChange={setScene} options={[{ value: 'IMAGE', label: '图文' }, { value: 'VIDEO', label: '视频' }]} /><Button icon={<ReloadOutlined />} onClick={load}>刷新</Button><Button type="primary" icon={<PlusOutlined />} onClick={() => { setEditing(null); setEditorOpen(true); }}>新建模板</Button></Space>} /><Card><Table loading={loading} rowKey={(record) => String(record.id)} dataSource={templates} pagination={{ total }} columns={[{ title: '场景', dataIndex: 'scene', render: (value) => sceneLabels[value as AIGenerationType] || value }, { title: '版本', dataIndex: 'version', render: (value) => `v${value}` }, { title: '模板内容', dataIndex: 'content', ellipsis: true, render: (value) => <Typography.Text ellipsis={{ tooltip: value }} style={{ maxWidth: 460, display: 'inline-block' }}>{value}</Typography.Text> }, { title: '状态', dataIndex: 'status', render: statusTag }, { title: '更新时间', dataIndex: 'updatedAt', render: formatDate }, { title: '操作', render: (_, template) => <Space><Button type="link" icon={<EditOutlined />} onClick={() => { setEditing(template); setEditorOpen(true); }}>编辑</Button><Button type="link" icon={<RollbackOutlined />} disabled={String(template.status) === 'ACTIVE' || String(template.status) === '1'} onClick={() => Modal.confirm({ title: `回滚到 v${template.version}？`, content: '回滚会重新启用这个历史版本，当前启用版本将停用。', onOk: () => rollback(template) })}>回滚</Button></Space> }]} /></Card><PromptEditor open={editorOpen} template={editing} onClose={() => setEditorOpen(false)} onSuccess={load} /></Space>;
}

function MonitorDetail({ item, open, onClose }: { item: GenerationTaskMonitor | null; open: boolean; onClose: () => void }) { return <Modal title="生成任务快照" open={open} onCancel={onClose} footer={<Button onClick={onClose}>关闭</Button>}>{item && <DescriptionsLike item={item} />}</Modal>; }
function DescriptionsLike({ item }: { item: GenerationTaskMonitor }) { return <div className="monitor-detail"><Row gutter={[12, 16]}><Col span={12}><Typography.Text type="secondary">任务 ID</Typography.Text><div>{String(item.taskId || item.id)}</div></Col><Col span={12}><Typography.Text type="secondary">作品 ID</Typography.Text><div>{item.workId ? String(item.workId) : '-'}</div></Col><Col span={12}><Typography.Text type="secondary">类型</Typography.Text><div>{sceneLabels[item.type]}</div></Col><Col span={12}><Typography.Text type="secondary">状态</Typography.Text><div>{statusTag(item.status)}</div></Col><Col span={12}><Typography.Text type="secondary">门店</Typography.Text><div>{item.storeName || '-'}</div></Col><Col span={12}><Typography.Text type="secondary">员工</Typography.Text><div>{item.userName || '-'}</div></Col><Col span={24}><Typography.Text type="secondary">风格 / 平台</Typography.Text><div>{item.styleName || '-'} / {item.platform || '-'}</div></Col><Col span={24}><Typography.Text type="secondary">原始输入</Typography.Text><div className="snapshot-text">{item.userInput || '-'}</div></Col><Col span={24}><Typography.Text type="secondary">失败原因</Typography.Text><div className="snapshot-text">{item.errorMessage || item.errorCode || '无'}</div></Col></Row></div>; }

export function GenerationTasksPage() {
  const [items, setItems] = useState<GenerationTaskMonitor[]>([]); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(false); const [selected, setSelected] = useState<GenerationTaskMonitor | null>(null); const [detailOpen, setDetailOpen] = useState(false); const [query, setQuery] = useState<GenerationTaskQuery>({ pageNo: 1, pageSize: 20 });
  const load = () => { setLoading(true); sharedApi.getGenerationTasks(query).then((result) => { setItems(result.list); setTotal(result.total); }).catch((error) => message.error(error instanceof Error ? error.message : '生成任务加载失败')).finally(() => setLoading(false)); }; useEffect(load, [query]);
  return <Space direction="vertical" size={20} className="full-width"><PageHeading title="生成任务监控" description="查看生成状态、失败原因和当时提交的原始意图，辅助运营排查问题。" action={<Button icon={<ReloadOutlined />} onClick={load}>刷新</Button>} /><Card><div className="table-toolbar"><div className="toolbar-left"><Select allowClear placeholder="状态" style={{ width: 120 }} onChange={(status) => setQuery((old) => ({ ...old, status, pageNo: 1 }))} options={[{ value: 'PROCESSING', label: '生成中' }, { value: 'SUCCESS', label: '成功' }, { value: 'FAILED', label: '失败' }]} /><Select allowClear placeholder="类型" style={{ width: 120 }} onChange={(type) => setQuery((old) => ({ ...old, type, pageNo: 1 }))} options={[{ value: 'IMAGE', label: '图文' }, { value: 'VIDEO', label: '视频' }]} /><DatePicker.RangePicker onChange={(dates) => setQuery((old) => ({ ...old, startDate: dates?.[0]?.format('YYYY-MM-DD'), endDate: dates?.[1]?.format('YYYY-MM-DD'), pageNo: 1 }))} /></div></div><Table loading={loading} rowKey={(record) => String(record.id)} dataSource={items} pagination={{ current: query.pageNo, pageSize: query.pageSize, total, onChange: (pageNo, pageSize) => setQuery((old) => ({ ...old, pageNo, pageSize })) }} rowClassName={(record) => String(record.status) === 'FAILED' || String(record.status) === '2' ? 'monitor-failed-row' : ''} columns={[{ title: '时间', dataIndex: 'createdAt', render: formatDate }, { title: '类型', dataIndex: 'type', render: (value) => sceneLabels[value as AIGenerationType] || value }, { title: '门店', dataIndex: 'storeName', render: (value) => value || '-' }, { title: '员工', dataIndex: 'userName', render: (value) => value || '-' }, { title: '耗时', dataIndex: 'duration', render: (value) => value ? `${value}s` : '-' }, { title: '状态', dataIndex: 'status', render: statusTag }, { title: '失败原因', dataIndex: 'errorMessage', render: (value, item) => value || item.errorCode || '-' }, { title: '操作', render: (_, item) => <Button type="link" icon={<EyeOutlined />} onClick={() => { setSelected(item); setDetailOpen(true); }}>查看快照</Button> }]} /></Card><MonitorDetail item={selected} open={detailOpen} onClose={() => setDetailOpen(false)} /></Space>;
}
