import { Button, Card, Checkbox, Col, DatePicker, Form, Input, Modal, Progress, Row, Select, Space, Table, Tabs, Tag, Typography, message } from 'antd';
import { PlusOutlined, ReloadOutlined } from '@ant-design/icons';
import type { ReactNode } from 'react';
import { useEffect, useState } from 'react';
import type { CreateTaskRequest, StoreBoard, Task } from '@xiaoa/share/types';
import { sharedApi } from '../services/sharedApi';

interface CrudPageProps { title: string; description: string; columns: string[]; }
function today() { return new Date().toISOString().slice(0, 10); }
function Heading({ title, description, action }: { title: string; description: string; action?: ReactNode }) { return <div className="page-heading"><div className="page-heading-copy"><Typography.Title level={2}>{title}</Typography.Title><Typography.Text>{description}</Typography.Text></div><div className="page-actions">{action}</div></div>; }

function TasksPage() {
  const [tasks, setTasks] = useState<Task[]>([]);
  const [board, setBoard] = useState<StoreBoard | null>(null);
  const [open, setOpen] = useState(false);
  const [form] = Form.useForm<CreateTaskRequest>();
  const [error, setError] = useState('');
  const storeId = localStorage.getItem('storeId');
  const load = () => { sharedApi.getMyTasks().then(setTasks).catch((requestError) => setError(requestError instanceof Error ? requestError.message : '任务加载失败')); if (storeId) sharedApi.getStoreBoard(storeId, today()).then(setBoard).catch((requestError) => setError(requestError instanceof Error ? requestError.message : '看板加载失败')); };
  useEffect(load, [storeId]);
  const submit = async (values: CreateTaskRequest & { startAt?: string; endAt?: string }) => { try { await sharedApi.createTask({ ...values, targetIds: values.targetIds || [] }); message.success('任务已创建'); setOpen(false); form.resetFields(); load(); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : '任务创建失败'); } };
  const toggle = async (task: Task) => { try { await sharedApi.updateTaskStatus(task.id, { status: task.status === 1 ? 2 : 1 }); load(); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : '任务状态更新失败'); } };
  return <Space direction="vertical" size={22} className="full-width"><Heading title="任务管理" description="按接口创建任务、启停任务并查看门店执行看板" action={<><Button icon={<ReloadOutlined />} onClick={load}>刷新</Button><Button type="primary" icon={<PlusOutlined />} onClick={() => setOpen(true)}>新建任务</Button></>} />{error && <Typography.Text type="danger">{error}</Typography.Text>}<Card><Tabs items={[{ key: 'tasks', label: '任务列表', children: <Table rowKey={(record) => String(record.id)} dataSource={tasks} columns={[{ title: '任务名称', dataIndex: 'title' }, { title: '平台', dataIndex: 'platform', render: (value) => value || '-' }, { title: '周期', dataIndex: 'frequency', render: (value) => ['-', '每日', '每周', '每月'][value] }, { title: '状态', dataIndex: 'status', render: (value) => <Tag color={value === 1 ? 'green' : 'default'}>{value === 1 ? '生效' : '停用'}</Tag> }, { title: '操作', render: (_, task: Task) => <Button type="link" onClick={() => toggle(task)}>{task.status === 1 ? '停用' : '启用'}</Button> }]} pagination={{ pageSize: 8 }} /> }, { key: 'board', label: '执行看板', children: board ? <><Progress percent={Math.round(board.completionRate * 100)} strokeColor="#c9a46c" /><Typography.Text>已完成 {board.finished} / 应完成 {board.expected}</Typography.Text><Table rowKey={(record) => String(record.id)} dataSource={board.unfinished} columns={[{ title: '记录 ID', dataIndex: 'id' }, { title: '任务 ID', dataIndex: 'taskId' }, { title: '员工 ID', dataIndex: 'userId' }, { title: '周期', dataIndex: 'periodDate' }]} /></> : <Typography.Text type="secondary">需要配置 `storeId` 后查询 /api/task/store-board</Typography.Text> }]} /></Card><Modal title="新建任务" open={open} onCancel={() => setOpen(false)} footer={null}><Form form={form} layout="vertical" onFinish={submit} initialValues={{ formType: 1, frequency: 1, targetScope: 1, targetIds: [], judgeType: 1 }}><Form.Item name="title" label="任务标题" rules={[{ required: true, message: '请输入任务标题' }]}><Input /></Form.Item><Form.Item name="formType" label="任务形式"><Select options={[{ label: '固定动作', value: 1 }, { label: '指定内容', value: 2 }]} /></Form.Item><Form.Item name="platform" label="发布平台"><Input placeholder="例如：朋友圈" /></Form.Item><Row gutter={12}><Col span={12}><Form.Item name="frequency" label="频率"><Select options={[{ label: '每日', value: 1 }, { label: '每周', value: 2 }, { label: '每月', value: 3 }]} /></Form.Item></Col><Col span={12}><Form.Item name="judgeType" label="完成判定"><Select options={[{ label: '点击即完成', value: 1 }, { label: '需要截图凭证', value: 2 }]} /></Form.Item></Col></Row><Form.Item name="targetScope" label="下发范围"><Select options={[{ label: '全员', value: 1 }, { label: '指定区域', value: 2 }, { label: '指定门店', value: 3 }, { label: '指定员工', value: 4 }]} /></Form.Item><Form.Item name="startAt" label="开始时间"><DatePicker showTime style={{ width: '100%' }} /></Form.Item><Form.Item name="endAt" label="结束时间"><DatePicker showTime style={{ width: '100%' }} /></Form.Item><Button type="primary" htmlType="submit">提交任务</Button></Form></Modal></Space>;
}

function StandardTablePage({ title, description, columns }: CrudPageProps) { return <Space direction="vertical" size={22} className="full-width"><Heading title={title} description={description} action={<Button type="primary" icon={<PlusOutlined />}>新建</Button>} /><Card><Table dataSource={[]} columns={columns.map((column) => ({ title: column, dataIndex: column }))} locale={{ emptyText: '该模块暂无 readme.md 中定义的接口' }} /></Card></Space>; }
function MaterialsPage({ title, description }: CrudPageProps) { return <StandardTablePage title={title} description={`${description} 当前 readme.md 未提供素材接口。`} columns={['素材名称', '类型', '来源', '操作']} />; }
function CalendarPage({ title, description }: CrudPageProps) { return <StandardTablePage title={title} description={`${description} 当前 readme.md 未提供内容包接口。`} columns={['内容包', '适用范围', '日期', '操作']} />; }
function QuotaPage({ title, description }: CrudPageProps) { return <StandardTablePage title={title} description={`${description} 当前任务域接口未提供额度接口。`} columns={['门店', '额度', '消耗', '余额']} />; }
function CompliancePage({ title, description }: CrudPageProps) { return <StandardTablePage title={title} description={`${description} 当前任务域接口未提供合规接口。`} columns={['词条', '风险级别', '适用范围', '更新时间']} />; }

export function CrudPage(props: CrudPageProps) { if (props.title === '任务管理') return <TasksPage />; if (props.title === '素材中心') return <MaterialsPage {...props} />; if (props.title === '营销日历') return <CalendarPage {...props} />; if (props.title === '算力总池') return <QuotaPage {...props} />; if (props.title === '合规中心') return <CompliancePage {...props} />; return <StandardTablePage {...props} />; }
