import { Alert, Button, Card, Col, Descriptions, Drawer, Form, Image, Input, InputNumber, Modal, Popconfirm, Row, Select, Space, Switch, Table, Tag, Typography, message } from 'antd';
import { CheckOutlined, CloseOutlined, EditOutlined, EyeOutlined, PlusOutlined, ReloadOutlined } from '@ant-design/icons';
import { useEffect, useState } from 'react';
import type { PlatformCustomer, PlatformCustomerRequest, PlatformPlan, PlatformPlanRequest, PlatformRechargeOrder, PlatformRechargeStatus, PlatformTenant, PlatformTenantStatus } from '@xiaoa/share/types';
import { sharedApi } from '../services/sharedApi';

interface PageProps { title: string; description: string; }
const statusLabels: Record<string, string> = { PENDING: '待审核', ACTIVE: '已开通', REJECTED: '已拒绝', DISABLED: '已停用', '0': '待审核', '1': '已开通', '2': '已拒绝', '3': '已停用', CONFIRMED: '已到账', VOIDED: '已作废' };
const statusColors: Record<string, string> = { PENDING: 'gold', ACTIVE: 'green', REJECTED: 'red', DISABLED: 'default', '0': 'gold', '1': 'green', '2': 'red', '3': 'default', CONFIRMED: 'green', VOIDED: 'default' };
function statusTag(status: string | number) { const key = String(status); return <Tag color={statusColors[key] || 'default'}>{statusLabels[key] || key}</Tag>; }
function formatDate(value?: string | null) { return value ? new Date(value).toLocaleDateString('zh-CN') : '-'; }
function PageHeading({ title, description, action }: PageProps & { action?: React.ReactNode }) { return <div className="page-heading"><div className="page-heading-copy"><Typography.Title level={2}>{title}</Typography.Title><Typography.Text>{description}</Typography.Text></div><div className="page-actions">{action}</div></div>; }
function useError() { const [error, setError] = useState(''); return { error, setError, catchError: (requestError: unknown, fallback: string) => setError(requestError instanceof Error ? requestError.message : fallback) }; }

function TenantDetail({ tenant, open, onClose }: { tenant: PlatformTenant | null; open: boolean; onClose: () => void }) {
  return <Drawer title="租户详情" width={620} open={open} onClose={onClose}>{tenant && <><Descriptions bordered column={1} size="small"><Descriptions.Item label="企业名称">{tenant.name}</Descriptions.Item><Descriptions.Item label="联系人">{tenant.contactName} / {tenant.contactPhone}</Descriptions.Item><Descriptions.Item label="统一社会信用代码">{tenant.unifiedSocialCreditCode || '-'}</Descriptions.Item><Descriptions.Item label="套餐">{tenant.planName || '-'}</Descriptions.Item><Descriptions.Item label="门店上限">{tenant.storeCount ?? 0} / {tenant.storeLimit ?? '-'}</Descriptions.Item><Descriptions.Item label="到期日">{formatDate(tenant.expireAt)}</Descriptions.Item><Descriptions.Item label="申请时间">{formatDate(tenant.applyAt)}</Descriptions.Item><Descriptions.Item label="申请备注">{tenant.applyRemark || '-'}</Descriptions.Item></Descriptions><Typography.Title level={5} style={{ marginTop: 24 }}>业务明细</Typography.Title><TabsForTenant /></>}</Drawer>;
}
function TabsForTenant() { return <div className="detail-tabs"><Typography.Text type="secondary">基本信息、门店列表、消耗流水、充值记录、操作日志</Typography.Text></div>; }

function TenantApproveModal({ tenant, open, onClose, onSuccess }: { tenant: PlatformTenant | null; open: boolean; onClose: () => void; onSuccess: () => void }) {
  const [form] = Form.useForm(); const [rejectOpen, setRejectOpen] = useState(false); const [loading, setLoading] = useState(false); const [rejectForm] = Form.useForm();
  useEffect(() => { if (tenant) form.setFieldsValue({ initialStoreLimit: tenant.storeLimit || 100, initialQuota: tenant.quotaTotal || 5000000, adminPhone: tenant.contactPhone }); }, [tenant, form]);
  const approve = async () => { try { const values = await form.validateFields(); setLoading(true); await sharedApi.approvePlatformTenant({ tenantId: tenant!.id, ...values }); message.success('租户已审核通过并开通'); onClose(); onSuccess(); } catch (error) { if (error instanceof Error) message.error(error.message); } finally { setLoading(false); } };
  const reject = async () => { try { const values = await rejectForm.validateFields(); setLoading(true); await sharedApi.rejectPlatformTenant({ tenantId: tenant!.id, reason: values.reason }); message.success('已拒绝该租户申请'); setRejectOpen(false); onClose(); onSuccess(); } catch (error) { if (error instanceof Error) message.error(error.message); } finally { setLoading(false); } };
  return <><Modal title="租户开通审核" open={open} onCancel={onClose} footer={null} destroyOnClose>{tenant && <Space direction="vertical" size={18} className="full-width"><Descriptions column={1} size="small"><Descriptions.Item label="企业名称">{tenant.name}</Descriptions.Item><Descriptions.Item label="统一社会信用代码">{tenant.unifiedSocialCreditCode || '-'}</Descriptions.Item><Descriptions.Item label="联系人">{tenant.contactName}　{tenant.contactPhone}</Descriptions.Item><Descriptions.Item label="申请套餐">{tenant.planName || '-'}</Descriptions.Item><Descriptions.Item label="营业执照">{tenant.licenseUrl ? <Image width={72} src={tenant.licenseUrl} /> : '-'}</Descriptions.Item><Descriptions.Item label="申请时间">{formatDate(tenant.applyAt)}</Descriptions.Item><Descriptions.Item label="申请备注">{tenant.applyRemark || '-'}</Descriptions.Item></Descriptions><Card size="small" title="开通配置（通过时填写）"><Form form={form} layout="vertical"><Row gutter={12}><Col span={12}><Form.Item name="initialStoreLimit" label="初始门店数上限" rules={[{ required: true }]}><InputNumber min={1} className="full-input" /></Form.Item></Col><Col span={12}><Form.Item name="initialQuota" label="初始积分额度" rules={[{ required: true }]}><InputNumber min={0} className="full-input" /></Form.Item></Col></Row><Form.Item name="adminPhone" label="超管账号手机号" rules={[{ required: true }]}><Input /></Form.Item></Form></Card><div className="modal-actions"><Button danger icon={<CloseOutlined />} onClick={() => setRejectOpen(true)}>拒绝</Button><Button type="primary" icon={<CheckOutlined />} loading={loading} onClick={approve}>审核通过并开通</Button></div></Space>}</Modal><Modal title="拒绝租户申请" open={rejectOpen} onCancel={() => setRejectOpen(false)} onOk={reject} confirmLoading={loading}><Form form={rejectForm}><Form.Item name="reason" rules={[{ required: true, message: '请填写拒绝原因' }]}><Input.TextArea rows={4} placeholder="请输入拒绝原因" /></Form.Item></Form></Modal></>;
}

export function PlatformTenantsPage({ title, description }: PageProps) {
  const [tenants, setTenants] = useState<PlatformTenant[]>([]); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(false); const [selected, setSelected] = useState<PlatformTenant | null>(null); const [approveOpen, setApproveOpen] = useState(false); const [detailOpen, setDetailOpen] = useState(false); const [query, setQuery] = useState<{ keyword?: string; status?: PlatformTenantStatus; pageNo?: number; pageSize?: number }>({ pageNo: 1, pageSize: 10 }); const { error, setError, catchError } = useError();
  const load = () => { setLoading(true); sharedApi.getPlatformTenants(query).then((result) => { setTenants(result.list); setTotal(result.total); }).catch((requestError) => catchError(requestError, '租户列表加载失败')).finally(() => setLoading(false)); }; useEffect(load, [query]);
  return <Space direction="vertical" size={20} className="full-width"><PageHeading title={title} description={description} action={<Button icon={<ReloadOutlined />} onClick={load}>刷新</Button>} />{error && <Typography.Text type="danger">{error}</Typography.Text>}<Card><div className="table-toolbar"><div className="toolbar-left"><Select allowClear placeholder="状态" style={{ width: 130 }} onChange={(status) => setQuery((old) => ({ ...old, status, pageNo: 1 }))} options={['PENDING', 'ACTIVE', 'REJECTED', 'DISABLED'].map((value) => ({ value, label: statusLabels[value] }))} /><Input.Search placeholder="搜索租户名/联系人" allowClear onSearch={(keyword) => setQuery((old) => ({ ...old, keyword, pageNo: 1 }))} style={{ width: 260 }} /></div><Typography.Text type="secondary">待审核 {tenants.filter((tenant) => String(tenant.status) === 'PENDING' || String(tenant.status) === '0').length} 家</Typography.Text></div><Table loading={loading} rowKey={(record) => String(record.id)} dataSource={tenants} pagination={{ current: query.pageNo, pageSize: query.pageSize, total, onChange: (pageNo, pageSize) => setQuery((old) => ({ ...old, pageNo, pageSize })) }} columns={[{ title: '租户名', dataIndex: 'name' }, { title: '联系人', dataIndex: 'contactName' }, { title: '手机号', dataIndex: 'contactPhone' }, { title: '套餐', dataIndex: 'planName', render: (value) => value || '-' }, { title: '状态', dataIndex: 'status', render: (value) => statusTag(value) }, { title: '到期日', dataIndex: 'expireAt', render: formatDate }, { title: '操作', render: (_, tenant) => <Space><Button type="link" icon={<EyeOutlined />} onClick={() => { setSelected(tenant); setDetailOpen(true); }}>详情</Button>{(String(tenant.status) === 'PENDING' || String(tenant.status) === '0') && <Button type="link" onClick={() => { setSelected(tenant); setApproveOpen(true); }}>审核</Button>}</Space> }]} /></Card><TenantDetail tenant={selected} open={detailOpen} onClose={() => setDetailOpen(false)} /><TenantApproveModal tenant={selected} open={approveOpen} onClose={() => setApproveOpen(false)} onSuccess={load} /></Space>;
}

function PlanDrawer({ open, plan, onClose, onSuccess }: { open: boolean; plan: PlatformPlan | null; onClose: () => void; onSuccess: () => void }) {
  const [form] = Form.useForm<PlatformPlanRequest>(); const [loading, setLoading] = useState(false); useEffect(() => { if (open) form.setFieldsValue(plan ? { ...plan } : { name: '', storeLimit: 3, quotaLimit: 50000, annualPrice: 9800, imagePrice: 5, videoPrice: 20, featureVideo: true, featureMaterialRecommend: true, featureApi: false }); }, [open, plan, form]);
  const submit = async (values: PlatformPlanRequest) => { try { setLoading(true); if (plan) await sharedApi.updatePlatformPlan(plan.id, values); else await sharedApi.createPlatformPlan(values); message.success(plan ? '套餐已更新' : '套餐已创建'); onClose(); onSuccess(); } catch (error) { if (error instanceof Error) message.error(error.message); } finally { setLoading(false); } };
  return <Drawer title={plan ? '编辑套餐' : '新建套餐'} width={520} open={open} onClose={onClose} extra={<Button type="primary" loading={loading} onClick={() => form.submit()}>保存</Button>} destroyOnClose><Form form={form} layout="vertical" onFinish={submit}><Form.Item name="name" label="套餐名称" rules={[{ required: true }]}><Input /></Form.Item><Row gutter={12}><Col span={12}><Form.Item name="storeLimit" label="门店数上限" rules={[{ required: true }]}><InputNumber min={1} className="full-input" /></Form.Item></Col><Col span={12}><Form.Item name="quotaLimit" label="年度积分额度" rules={[{ required: true }]}><InputNumber min={0} className="full-input" /></Form.Item></Col></Row><Form.Item name="annualPrice" label="年费（元）" rules={[{ required: true }]}><InputNumber min={0} className="full-input" /></Form.Item><Card size="small" title="积分单价说明"><Row gutter={12}><Col span={12}><Form.Item name="imagePrice" label="图文生成（积分/次）"><InputNumber min={0} className="full-input" /></Form.Item></Col><Col span={12}><Form.Item name="videoPrice" label="视频生成（积分/次）"><InputNumber min={0} className="full-input" /></Form.Item></Col></Row></Card><Form.Item label="功能开关"><Space direction="vertical"><Form.Item name="featureVideo" valuePropName="checked" noStyle><Switch checkedChildren="视频生成" unCheckedChildren="视频生成" /></Form.Item><Form.Item name="featureMaterialRecommend" valuePropName="checked" noStyle><Switch checkedChildren="素材推优" unCheckedChildren="素材推优" /></Form.Item><Form.Item name="featureApi" valuePropName="checked" noStyle><Switch checkedChildren="API 对接" unCheckedChildren="API 对接" /></Form.Item></Space></Form.Item><Form.Item name="description" label="套餐说明"><Input.TextArea rows={4} /></Form.Item></Form></Drawer>;
}

export function PlatformPlansPage({ title, description }: PageProps) { const [plans, setPlans] = useState<PlatformPlan[]>([]); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(false); const [drawerOpen, setDrawerOpen] = useState(false); const [editing, setEditing] = useState<PlatformPlan | null>(null); const load = () => { setLoading(true); sharedApi.getPlatformPlans({ pageNo: 1, pageSize: 50 }).then((result) => { setPlans(result.list); setTotal(result.total); }).catch(() => message.error('套餐列表加载失败')).finally(() => setLoading(false)); }; useEffect(load, []); return <Space direction="vertical" size={20} className="full-width"><PageHeading title={title} description={description} action={<Button type="primary" icon={<PlusOutlined />} onClick={() => { setEditing(null); setDrawerOpen(true); }}>新建套餐</Button>} /><Card><Table loading={loading} rowKey={(record) => String(record.id)} dataSource={plans} pagination={{ total }} columns={[{ title: '套餐名', dataIndex: 'name' }, { title: '门店上限', dataIndex: 'storeLimit' }, { title: '积分/年', dataIndex: 'quotaLimit', render: (value) => value.toLocaleString() }, { title: '价格/年', dataIndex: 'annualPrice', render: (value) => `¥${value.toLocaleString()}` }, { title: '状态', dataIndex: 'status', render: (value) => statusTag(value) }, { title: '使用中', dataIndex: 'usedCount', render: (value) => value ?? 0 }, { title: '操作', render: (_, plan) => <Space><Button type="link" icon={<EditOutlined />} onClick={() => { setEditing(plan); setDrawerOpen(true); }}>编辑</Button><Popconfirm title={String(plan.status) === 'ACTIVE' || String(plan.status) === '1' ? '停用后新租户不可选择，确认停用？' : '确认上架该套餐？'} onConfirm={() => sharedApi.updatePlatformPlanStatus(plan.id, String(plan.status) === 'ACTIVE' || String(plan.status) === '1' ? 'INACTIVE' : 'ACTIVE').then(load).catch(() => message.error('套餐状态更新失败'))}><Button type="link">{String(plan.status) === 'ACTIVE' || String(plan.status) === '1' ? '停用' : '上架'}</Button></Popconfirm></Space> }]} /></Card><PlanDrawer open={drawerOpen} plan={editing} onClose={() => setDrawerOpen(false)} onSuccess={load} /></Space>; }

function RechargeModal({ order, open, onClose, onSuccess }: { order: PlatformRechargeOrder | null; open: boolean; onClose: () => void; onSuccess: () => void }) { const [balance, setBalance] = useState<{ currentBalance: number; balanceAfter: number } | null>(null); const [voidOpen, setVoidOpen] = useState(false); const [form] = Form.useForm(); const [loading, setLoading] = useState(false); useEffect(() => { if (open && order) { setBalance(null); sharedApi.getPlatformRechargeBalance(order.id).then(setBalance).catch(() => setBalance({ currentBalance: order.currentBalance || 0, balanceAfter: (order.currentBalance || 0) + order.amount })); } }, [open, order]); const confirm = async () => { try { setLoading(true); await sharedApi.confirmPlatformRecharge({ rechargeId: order!.id }); message.success('充值已确认到账'); onClose(); onSuccess(); } catch (error) { if (error instanceof Error) message.error(error.message); } finally { setLoading(false); } }; const voidOrder = async () => { try { const values = await form.validateFields(); setLoading(true); await sharedApi.voidPlatformRecharge({ rechargeId: order!.id, reason: values.reason }); message.success('充值单已作废'); setVoidOpen(false); onClose(); onSuccess(); } catch (error) { if (error instanceof Error) message.error(error.message); } finally { setLoading(false); } }; return <><Modal title={`确认到账 - ${order?.orderNo || ''}`} open={open} onCancel={onClose} footer={null} destroyOnClose>{order && <Space direction="vertical" size={18} className="full-width"><Descriptions column={1} size="small"><Descriptions.Item label="租户">{order.tenantName}</Descriptions.Item><Descriptions.Item label="充值金额">¥{order.amount.toLocaleString()}</Descriptions.Item><Descriptions.Item label="转账凭证">{order.proofUrl ? <Image width={100} src={order.proofUrl} /> : '-'}</Descriptions.Item><Descriptions.Item label="提交人">{order.submitterName || '-'} / {formatDate(order.submittedAt)}</Descriptions.Item></Descriptions>{balance && <Alert message={`确认后 ¥${order.amount.toLocaleString()} 将入 ${order.tenantName} 总池`} description={`当前总池余额 ¥${balance.currentBalance.toLocaleString()} → ¥${balance.balanceAfter.toLocaleString()}`} type="warning" showIcon />}<div className="modal-actions"><Button onClick={() => setVoidOpen(true)}>作废</Button><Popconfirm title="确认充值到账？" description="确认后将写入总池和额度流水，且不可重复确认。" onConfirm={confirm}><Button type="primary" loading={loading} icon={<CheckOutlined />}>确认到账</Button></Popconfirm></div></Space>}</Modal><Modal title="作废充值单" open={voidOpen} onCancel={() => setVoidOpen(false)} onOk={voidOrder} confirmLoading={loading}><Form form={form}><Form.Item name="reason" rules={[{ required: true, message: '请填写作废原因' }]}><Input.TextArea rows={4} /></Form.Item></Form></Modal></>; }

export function PlatformRechargesPage({ title, description }: PageProps) { const [orders, setOrders] = useState<PlatformRechargeOrder[]>([]); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(false); const [selected, setSelected] = useState<PlatformRechargeOrder | null>(null); const [open, setOpen] = useState(false); const [status, setStatus] = useState<PlatformRechargeStatus | undefined>('PENDING'); const load = () => { setLoading(true); sharedApi.getPlatformRecharges({ pageNo: 1, pageSize: 20, status }).then((result) => { setOrders(result.list); setTotal(result.total); }).catch(() => message.error('充值列表加载失败')).finally(() => setLoading(false)); }; useEffect(load, [status]); return <Space direction="vertical" size={20} className="full-width"><PageHeading title={title} description={description} action={<Space><Tag color="gold">待确认 {orders.filter((order) => String(order.status) === 'PENDING' || String(order.status) === '0').length} 笔</Tag><Button icon={<ReloadOutlined />} onClick={load}>刷新</Button></Space>} /><Card><div className="table-toolbar"><Select value={status} onChange={setStatus} style={{ width: 130 }} options={[{ value: 'PENDING', label: '待确认' }, { value: 'CONFIRMED', label: '已到账' }, { value: 'VOIDED', label: '已作废' }]} /></div><Table loading={loading} rowKey={(record) => String(record.id)} dataSource={orders} pagination={{ total }} columns={[{ title: '充值单号', dataIndex: 'orderNo' }, { title: '租户', dataIndex: 'tenantName' }, { title: '金额', dataIndex: 'amount', render: (value) => `¥${value.toLocaleString()}` }, { title: '凭证', dataIndex: 'proofUrl', render: (value) => value ? <Image width={48} src={value} /> : '-' }, { title: '状态', dataIndex: 'status', render: (value) => statusTag(value) }, { title: '操作', render: (_, order) => <Button type="link" onClick={() => { setSelected(order); setOpen(true); }}>{String(order.status) === 'PENDING' || String(order.status) === '0' ? '确认到账' : '详情'}</Button> }]} /></Card><RechargeModal order={selected} open={open} onClose={() => setOpen(false)} onSuccess={load} /></Space>; }

function CustomerDrawer({ open, customer, onClose, onSuccess }: { open: boolean; customer: PlatformCustomer | null; onClose: () => void; onSuccess: () => void }) { const [form] = Form.useForm<PlatformCustomerRequest>(); const [loading, setLoading] = useState(false); useEffect(() => { if (open) form.setFieldsValue(customer ? { tenantId: customer.tenantId, name: customer.name, role: customer.role, phone: customer.phone, remark: customer.remark } : { role: '超管' }); }, [open, customer, form]); const submit = async (values: PlatformCustomerRequest) => { try { setLoading(true); if (customer) await sharedApi.updatePlatformCustomer(customer.id, values); else await sharedApi.createPlatformCustomer(values); message.success(customer ? '联系人已更新' : '联系人已创建'); onClose(); onSuccess(); } catch (error) { if (error instanceof Error) message.error(error.message); } finally { setLoading(false); } }; return <Drawer title={customer ? '编辑联系人' : '新建联系人'} open={open} onClose={onClose} width={460} extra={<Button type="primary" loading={loading} onClick={() => form.submit()}>保存</Button>}><Form form={form} layout="vertical" onFinish={submit}><Form.Item name="tenantId" label="租户 ID" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="name" label="联系人" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="role" label="角色" rules={[{ required: true }]}><Select options={['超管', '财务', '运营'].map((value) => ({ label: value, value }))} /></Form.Item><Form.Item name="phone" label="手机号" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="remark" label="跟进备注"><Input.TextArea rows={4} /></Form.Item></Form></Drawer>; }
export function PlatformCustomersPage({ title, description }: PageProps) { const [customers, setCustomers] = useState<PlatformCustomer[]>([]); const [loading, setLoading] = useState(false); const [total, setTotal] = useState(0); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<PlatformCustomer | null>(null); const load = () => { setLoading(true); sharedApi.getPlatformCustomers({ pageNo: 1, pageSize: 20 }).then((result) => { setCustomers(result.list); setTotal(result.total); }).catch(() => message.error('客户列表加载失败')).finally(() => setLoading(false)); }; useEffect(load, []); return <Space direction="vertical" size={20} className="full-width"><PageHeading title={title} description={description} action={<Button type="primary" icon={<PlusOutlined />} onClick={() => { setEditing(null); setOpen(true); }}>新建联系人</Button>} /><Card><Table loading={loading} rowKey={(record) => String(record.id)} dataSource={customers} pagination={{ total }} columns={[{ title: '租户', dataIndex: 'tenantName' }, { title: '联系人', dataIndex: 'name' }, { title: '角色', dataIndex: 'role' }, { title: '手机', dataIndex: 'phone' }, { title: '最近登录', dataIndex: 'lastLoginAt', render: formatDate }, { title: '备注', dataIndex: 'remark', ellipsis: true }, { title: '操作', render: (_, customer) => <Space><Button type="link" onClick={() => { setEditing(customer); setOpen(true); }}>编辑</Button><Popconfirm title="确认删除联系人？" onConfirm={() => sharedApi.deletePlatformCustomer(customer.id).then(load).catch(() => message.error('删除失败'))}><Button type="link" danger>删除</Button></Popconfirm></Space> }]} /></Card><CustomerDrawer open={open} customer={editing} onClose={() => setOpen(false)} onSuccess={load} /></Space>; }
