import type {
  AdminTaskReport,
  AsyncTask,
  AuthJoinRequest,
  AuthJoinResult,
  AuthLoginRequest,
  AuthMe,
  AuthSession,
  AuthTakeoverRequest,
  Badge,
  BadgeQuery,
  ChatResult,
  CreateInviteRequest,
  CreateOrgRequest,
  CreateTaskRequest,
  CreationConfig,
  GenerateResult,
  GenerateWorkRequest,
  GenerationTaskMonitor,
  GenerationTaskQuery,
  PageResult,
  PromptTemplate,
  PromptTemplateQuery,
  PromptTemplateRequest,
  PublishRecord,
  Quota,
  RankingItem,
  RankingQuery,
  RemindTaskRequest,
  TaskBoard,
  TaskBoardRecord,
  TaskStoreSummary,
  PlatformCustomer,
  PlatformCustomerListQuery,
  PlatformCustomerRequest,
  PlatformDashboard,
  PlatformPeriod,
  PlatformPlan,
  PlatformPlanRequest,
  PlatformRechargeConfirmRequest,
  PlatformRechargeListQuery,
  PlatformRechargeOrder,
  PlatformRechargeVoidRequest,
  PlatformTenant,
  PlatformTenantApproveRequest,
  PlatformTenantListQuery,
  PlatformTenantRejectRequest,
  RequestAdapter,
  RequestOptions,
  StoreBoard,
  TenantDetail,
  TenantOpenRequest,
  TenantOpenResult,
  UpdateOrgNameRequest,
  UpdateUserRoleRequest,
  GrantUserRoleRequest,
  Invite,
  OrgNode,
  WorkStatusResponse,
  Task,
  TaskModifyLog,
  TaskSummary,
  TaskStatusRequest,
  UpdateTaskRequest,
  User,
  Work,
} from './types';

export function createApi(adapter: RequestAdapter) {
  const request = <T>(url: string, options?: RequestOptions) => adapter.request<T>(url, options);

  return {
    request,
    health: () => request<{ status: string }>('/health'),
    getUser: () => request<User>('/user'),
    openTenant: (data: TenantOpenRequest) => request<TenantOpenResult>('/tenants/open', { method: 'POST', data }),
    getTenant: (tenantId: number | string) => request<TenantDetail>(`/tenants/${tenantId}`),
    login: (data: AuthLoginRequest) => request<AuthSession>('/auth/login', { method: 'POST', data }),
    joinByInvite: (data: AuthJoinRequest) => request<AuthJoinResult>('/auth/join', { method: 'POST', data }),
    takeover: (data: AuthTakeoverRequest) => request<AuthSession>('/auth/takeover', { method: 'POST', data }),
    logout: () => request<void>('/auth/logout', { method: 'POST' }),
    getAuthMe: () => request<AuthMe>('/auth/me'),
    createInvite: (data: CreateInviteRequest) => request<Invite>('/invites', { method: 'POST', data }),
    validateInvite: (code: string) => request<Invite>(`/invites/${encodeURIComponent(code)}`),
    createOrg: (data: CreateOrgRequest) => request<OrgNode>('/orgs', { method: 'POST', data }),
    getOrgTree: () => request<OrgNode[]>('/orgs/tree'),
    updateOrgName: (orgId: number | string, data: UpdateOrgNameRequest) => request<void>(`/orgs/${orgId}/name`, { method: 'PATCH', data }),
    removeMember: (roleId: number | string) => request<void>(`/users/roles/${roleId}`, { method: 'DELETE' }),
    disableUser: (userId: number | string) => request<void>(`/users/${userId}/disable`, { method: 'PATCH' }),
    grantUserRole: (userId: number | string, data: GrantUserRoleRequest) => request<void>(`/users/${userId}/roles`, { method: 'PUT', data }),
    updateUserRole: (roleId: number | string, data: UpdateUserRoleRequest) => request<void>(`/users/roles/${roleId}`, { method: 'PATCH', data }),
    getQuota: () => request<Quota>('/quota'),
    getTaskSummary: () => request<TaskSummary>('/task-summary'),
    getMyTasks: () => request<Task[]>('/task/my'),
    getTask: (taskId: number | string) => request<Task>(`/task/${taskId}`),
    createTask: (data: CreateTaskRequest) => request<Task>('/task', { method: 'POST', data }),
    updateTask: (taskId: number | string, data: UpdateTaskRequest) => request<Task>(`/task/${taskId}`, { method: 'PUT', data }),
    updateTaskStatus: (taskId: number | string, data: TaskStatusRequest) => request<void>(`/task/${taskId}/status`, { method: 'PATCH', data }),
    getTaskModifyLogs: (taskId: number | string) => request<TaskModifyLog[]>(`/task/${taskId}/modify-logs`),
    getStoreBoard: (storeId: number | string, periodDate: string) => request<StoreBoard>(`/task/store-board?storeId=${encodeURIComponent(storeId)}&periodDate=${encodeURIComponent(periodDate)}`),
    remindTask: (data: RemindTaskRequest) => request<number>('/task/remind', { method: 'POST', data }),
    getTaskBoard: (date: string) => request<TaskBoard>(`/task/board?date=${encodeURIComponent(date)}`),
    getTaskStoreSummary: (taskId: number | string, date: string) => request<TaskStoreSummary[]>(`/task/board/stores?taskId=${encodeURIComponent(taskId)}&date=${encodeURIComponent(date)}`),
    getTaskBoardRecords: (taskId: number | string, storeId: number | string, date: string) => request<TaskBoardRecord[]>(`/task/board/records?taskId=${encodeURIComponent(taskId)}&storeId=${encodeURIComponent(storeId)}&date=${encodeURIComponent(date)}`),
    getAdminTaskReport: (taskId: number | string, params?: { storeId?: number | string; periodDate?: string }) => {
      const query = params ? `?${Object.entries(params).map(([key, value]) => `${key}=${encodeURIComponent(String(value))}`).join('&')}` : '';
      return request<AdminTaskReport>(`/admin/task/${taskId}/report${query}`);
    },
    getTaskRanking: (params: RankingQuery = {}) => {
      const query = Object.entries(params).map(([key, value]) => `${key}=${encodeURIComponent(String(value))}`).join('&');
      return request<RankingItem[]>(`/task/ranking${query ? `?${query}` : ''}`);
    },
    getTaskBadges: (params: BadgeQuery = {}) => {
      const query = Object.entries(params).map(([key, value]) => `${key}=${encodeURIComponent(String(value))}`).join('&');
      return request<Badge[]>(`/task/badges${query ? `?${query}` : ''}`);
    },
    chat: (message: string, taskId?: number | string) => request<ChatResult>('/chat', { method: 'POST', data: { message, ...(taskId ? { taskId } : {}), industry: 'jewelry-marriage' } }),
    getCreationConfig: () => request<CreationConfig>('/creation/config'),
    generate: (data: GenerateWorkRequest) => request<GenerateResult>('/work/generate', { method: 'POST', data }),
    getWorkStatus: (workId: number | string) => request<WorkStatusResponse>(`/work/${workId}/status`),
    getAsyncTask: (taskId: string) => request<AsyncTask>(`/task/${taskId}`),
    getPromptTemplates: (params: PromptTemplateQuery = {}) => request<PageResult<PromptTemplate>>('/admin/prompt-template/list', { data: params }),
    createPromptTemplate: (data: PromptTemplateRequest) => request<PromptTemplate>('/admin/prompt-template', { method: 'POST', data }),
    rollbackPromptTemplate: (templateId: number | string) => request<PromptTemplate>(`/admin/prompt-template/${templateId}/rollback`, { method: 'PUT' }),
    getGenerationTasks: (params: GenerationTaskQuery = {}) => request<PageResult<GenerationTaskMonitor>>('/admin/generation-task/list', { data: params }),
    getWorks: (pageNo = 1, pageSize = 20) => request<PageResult<Work>>('/works', { data: { pageNo, pageSize, industry: 'jewelry-marriage' } }),
    publishRecord: (data: PublishRecord) => request<void>('/publish-record', { method: 'POST', data }),
    getPlatformDashboard: (period: PlatformPeriod = 'month') => request<PlatformDashboard>(`/platform/dashboard?period=${encodeURIComponent(period)}`),
    getPlatformTenants: (params: PlatformTenantListQuery = {}) => request<PageResult<PlatformTenant>>('/platform/tenant/list', { data: params }),
    approvePlatformTenant: (data: PlatformTenantApproveRequest) => request<PlatformTenant>('/platform/tenant/approve', { method: 'POST', data }),
    rejectPlatformTenant: (data: PlatformTenantRejectRequest) => request<PlatformTenant>('/platform/tenant/reject', { method: 'POST', data }),
    getPlatformPlans: (params: { pageNo?: number; pageSize?: number; status?: string } = {}) => request<PageResult<PlatformPlan>>('/platform/plan/list', { data: params }),
    createPlatformPlan: (data: PlatformPlanRequest) => request<PlatformPlan>('/platform/plan', { method: 'POST', data }),
    updatePlatformPlan: (planId: number | string, data: PlatformPlanRequest) => request<PlatformPlan>(`/platform/plan/${planId}`, { method: 'PUT', data }),
    updatePlatformPlanStatus: (planId: number | string, status: 'ACTIVE' | 'INACTIVE' | 0 | 1) => request<PlatformPlan>(`/platform/plan/${planId}/status`, { method: 'PATCH', data: { status } }),
    getPlatformRecharges: (params: PlatformRechargeListQuery = {}) => request<PageResult<PlatformRechargeOrder>>('/platform/recharge/list', { data: params }),
    getPlatformRechargeBalance: (rechargeId: number | string) => request<{ currentBalance: number; balanceAfter: number }>(`/platform/recharge/${rechargeId}/balance`),
    confirmPlatformRecharge: (data: PlatformRechargeConfirmRequest) => request<PlatformRechargeOrder>('/platform/recharge/confirm', { method: 'POST', data }),
    voidPlatformRecharge: (data: PlatformRechargeVoidRequest) => request<PlatformRechargeOrder>('/platform/recharge/void', { method: 'POST', data }),
    getPlatformCustomers: (params: PlatformCustomerListQuery = {}) => request<PageResult<PlatformCustomer>>('/platform/customer/list', { data: params }),
    createPlatformCustomer: (data: PlatformCustomerRequest) => request<PlatformCustomer>('/platform/customer', { method: 'POST', data }),
    updatePlatformCustomer: (customerId: number | string, data: PlatformCustomerRequest) => request<PlatformCustomer>(`/platform/customer/${customerId}`, { method: 'PUT', data }),
    deletePlatformCustomer: (customerId: number | string) => request<void>(`/platform/customer/${customerId}`, { method: 'DELETE' }),
  };
}

export type ApiClient = ReturnType<typeof createApi>;
